spring:
  # redis配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456

sa-token:
  jwt-secret-key: asdasdasifhueuiwfdgdfgyurfewbfjsdafjk
  token-name: token

